/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as TicketIdRouteImport } from './routes/ticket.$id'
import { Route as StoreCreateRouteImport } from './routes/store.create'
import { Route as StoreIdRouteImport } from './routes/store.$id'
import { Route as ProfileEditRouteImport } from './routes/profile_.edit'
import { Route as StoreIdEditRouteImport } from './routes/store_.$id.edit'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketIdRoute = TicketIdRouteImport.update({
  id: '/ticket/$id',
  path: '/ticket/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreCreateRoute = StoreCreateRouteImport.update({
  id: '/store/create',
  path: '/store/create',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIdRoute = StoreIdRouteImport.update({
  id: '/store/$id',
  path: '/store/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile_/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIdEditRoute = StoreIdEditRouteImport.update({
  id: '/store_/$id/edit',
  path: '/store/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/profile/edit': typeof ProfileEditRoute
  '/store/$id': typeof StoreIdRoute
  '/store/create': typeof StoreCreateRoute
  '/ticket/$id': typeof TicketIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/store/$id/edit': typeof StoreIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/profile/edit': typeof ProfileEditRoute
  '/store/$id': typeof StoreIdRoute
  '/store/create': typeof StoreCreateRoute
  '/ticket/$id': typeof TicketIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/store/$id/edit': typeof StoreIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/profile_/edit': typeof ProfileEditRoute
  '/store/$id': typeof StoreIdRoute
  '/store/create': typeof StoreCreateRoute
  '/ticket/$id': typeof TicketIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/store_/$id/edit': typeof StoreIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/login'
    | '/profile'
    | '/profile/edit'
    | '/store/$id'
    | '/store/create'
    | '/ticket/$id'
    | '/vendor/dashboard'
    | '/store/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/login'
    | '/profile'
    | '/profile/edit'
    | '/store/$id'
    | '/store/create'
    | '/ticket/$id'
    | '/vendor/dashboard'
    | '/store/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/login'
    | '/profile'
    | '/profile_/edit'
    | '/store/$id'
    | '/store/create'
    | '/ticket/$id'
    | '/vendor/dashboard'
    | '/store_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ProfileEditRoute: typeof ProfileEditRoute
  StoreIdRoute: typeof StoreIdRoute
  StoreCreateRoute: typeof StoreCreateRoute
  TicketIdRoute: typeof TicketIdRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  StoreIdEditRoute: typeof StoreIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$id': {
      id: '/ticket/$id'
      path: '/ticket/$id'
      fullPath: '/ticket/$id'
      preLoaderRoute: typeof TicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/create': {
      id: '/store/create'
      path: '/store/create'
      fullPath: '/store/create'
      preLoaderRoute: typeof StoreCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$id': {
      id: '/store/$id'
      path: '/store/$id'
      fullPath: '/store/$id'
      preLoaderRoute: typeof StoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/edit': {
      id: '/profile_/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/$id/edit': {
      id: '/store_/$id/edit'
      path: '/store/$id/edit'
      fullPath: '/store/$id/edit'
      preLoaderRoute: typeof StoreIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ProfileEditRoute: ProfileEditRoute,
  StoreIdRoute: StoreIdRoute,
  StoreCreateRoute: StoreCreateRoute,
  TicketIdRoute: TicketIdRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  StoreIdEditRoute: StoreIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
