/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as ProtectedRouteImport } from './routes/protected.tsx'
import { Route as ProfileRouteImport } from './routes/profile.tsx'
import { Route as LoginRouteImport } from './routes/login.tsx'
import { Route as ExampleRouteImport } from './routes/example.tsx'
import { Route as ActivityRouteImport } from './routes/activity.tsx'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard.tsx'
import { Route as TicketIdRouteImport } from './routes/ticket.$id.tsx'
import { Route as StoreCreateRouteImport } from './routes/store.create.tsx'
import { Route as StoreIdRouteImport } from './routes/store.$id.tsx'
import { Route as ProfileEditRouteImport } from './routes/profile.edit.tsx'
import { Route as StoreIdEditRouteImport } from './routes/store.$id.edit.tsx'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/protected',
  path: '/protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleRoute = ExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketIdRoute = TicketIdRouteImport.update({
  id: '/ticket/$id',
  path: '/ticket/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreCreateRoute = StoreCreateRouteImport.update({
  id: '/store/create',
  path: '/store/create',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIdRoute = StoreIdRouteImport.update({
  id: '/store/$id',
  path: '/store/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const StoreIdEditRoute = StoreIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => StoreIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/example': typeof ExampleRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/protected': typeof ProtectedRoute
  '/profile/edit': typeof ProfileEditRoute
  '/store/$id': typeof StoreIdRouteWithChildren
  '/store/create': typeof StoreCreateRoute
  '/ticket/$id': typeof TicketIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/store/$id/edit': typeof StoreIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/example': typeof ExampleRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/protected': typeof ProtectedRoute
  '/profile/edit': typeof ProfileEditRoute
  '/store/$id': typeof StoreIdRouteWithChildren
  '/store/create': typeof StoreCreateRoute
  '/ticket/$id': typeof TicketIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/store/$id/edit': typeof StoreIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/example': typeof ExampleRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/protected': typeof ProtectedRoute
  '/profile/edit': typeof ProfileEditRoute
  '/store/$id': typeof StoreIdRouteWithChildren
  '/store/create': typeof StoreCreateRoute
  '/ticket/$id': typeof TicketIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/store/$id/edit': typeof StoreIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/example'
    | '/login'
    | '/profile'
    | '/protected'
    | '/profile/edit'
    | '/store/$id'
    | '/store/create'
    | '/ticket/$id'
    | '/vendor/dashboard'
    | '/store/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/example'
    | '/login'
    | '/profile'
    | '/protected'
    | '/profile/edit'
    | '/store/$id'
    | '/store/create'
    | '/ticket/$id'
    | '/vendor/dashboard'
    | '/store/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/example'
    | '/login'
    | '/profile'
    | '/protected'
    | '/profile/edit'
    | '/store/$id'
    | '/store/create'
    | '/ticket/$id'
    | '/vendor/dashboard'
    | '/store/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ExampleRoute: typeof ExampleRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ProtectedRoute: typeof ProtectedRoute
  StoreIdRoute: typeof StoreIdRouteWithChildren
  StoreCreateRoute: typeof StoreCreateRoute
  TicketIdRoute: typeof TicketIdRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/protected': {
      id: '/protected'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example': {
      id: '/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$id': {
      id: '/ticket/$id'
      path: '/ticket/$id'
      fullPath: '/ticket/$id'
      preLoaderRoute: typeof TicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/create': {
      id: '/store/create'
      path: '/store/create'
      fullPath: '/store/create'
      preLoaderRoute: typeof StoreCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$id': {
      id: '/store/$id'
      path: '/store/$id'
      fullPath: '/store/$id'
      preLoaderRoute: typeof StoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/store/$id/edit': {
      id: '/store/$id/edit'
      path: '/edit'
      fullPath: '/store/$id/edit'
      preLoaderRoute: typeof StoreIdEditRouteImport
      parentRoute: typeof StoreIdRoute
    }
  }
}

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface StoreIdRouteChildren {
  StoreIdEditRoute: typeof StoreIdEditRoute
}

const StoreIdRouteChildren: StoreIdRouteChildren = {
  StoreIdEditRoute: StoreIdEditRoute,
}

const StoreIdRouteWithChildren =
  StoreIdRoute._addFileChildren(StoreIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ExampleRoute: ExampleRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ProtectedRoute: ProtectedRoute,
  StoreIdRoute: StoreIdRouteWithChildren,
  StoreCreateRoute: StoreCreateRoute,
  TicketIdRoute: TicketIdRoute,
  VendorDashboardRoute: VendorDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
